Functions
1. Define the function
2. Invoking the function
3. Passing the arguements

In [4]:
def cake_baker():
  print("I am ready to bake the cake")

cake_baker()

I am ready to bake the cake


In [8]:
def cake_baker(p,f,s):
  print("No of pieces =", p)
  print("Flavour is =", f)
  print("Size is =", s)

cake_baker("5","Chocolate","5kg")
cake_baker("2","Mangooo","2kg")

No of pieces = 5
Flavour is = Chocolate
Size is = 5kg
No of pieces = 2
Flavour is = Mangooo
Size is = 2kg


In [28]:
def add(*args):
  sum=0
  for i in args:
    sum=sum+i
  return sum
print(add(1,2,3,4,5))

15


In [32]:
def greet(**kwargs):
  print("HELLO")
  for key, value in kwargs.items():
    print(value, end=" ")

greet(name="Vickyyy", usn="01fe21bec003", branch="ECE")

HELLO
Vickyyy 01fe21bec003 ECE 

In [34]:
import random
x=random.randint(1,24)
print(x)

a=random.random()
print(a)

10
0.598631388248478


In [37]:
import random
computer=random.randint(1,99)
userinput=int(input("Enter the number between 1 and 99"))
print(computer)
print(userinput)

if computer>userinput:
  print("Computer WON")
elif computer==userinput:
  print("TIE")
else:
  print("You WON")

Enter the number between 1 and 99 26
72
26
Computer WON


In [47]:
import random
gamelist=['rock','paper','scissors']
comp=random.choice(gamelist)
user=input("Enter either rock or paper or scissors: ")
print(comp)
print(user)

if (comp=="rock" and user=="paper"):
  print("You won")
elif (comp=="rock" and user=="scissors"):
  print("Computer won")
elif (comp=="paper" and user=="rock"):
  print("Computer won")
elif (comp=="paper" and user=="scissors"):
  print("You won")
elif (comp=="scissors" and user=="rock"):
  print("You won")
elif(comp=="scissors" and user=="paper"):
  print("Computer won")

else:
  print("TIE")

Enter either rock or paper or scissors: paper
scissors
paper
Computer won


NumPy - Numerical Python

In [50]:
import numpy as np

In [52]:
a=np.array([35,4,56,34,27,53,46])
print(type(a))

<class 'numpy.ndarray'>


In [56]:
b= np.zeros(3)
c= np.ones(4)

print(b)
print(c)

[0. 0. 0.]
[1. 1. 1. 1.]


In [57]:
d=np.sort(a)
print(d)

[ 4 27 34 35 46 53 56]
